//Genres
export const FETCH_MOVIE_GENRES = 'FETCH_MOVIE_GENRES';
export const FETCH_SHOW_GENRES = 'FETCH_SHOW_GENRES';

//Movies
export const FETCH_UPCOMING_MOVIES = 'FETCH_UPCOMING_MOVIES';
export const FETCH_PLAYING_NOW_MOVIES = 'FETCH_PLAYING_NOW_MOVIES';
export const FETCH_TOP_RATED_MOVIES = 'FETCH_TOP_RATED_MOVIES';
export const FETCH_POPULAR_MOVIES = 'FETCH_POPULAR_MOVIES';
// export const FETCH_LATEST_MOVIE = 'FETCH_LATEST_MOVIE';

//Shows/TV
export const FETCH_SHOW_AIRING_TODAY_MOVIES = 'FETCH_SHOW_AIRING_TODAY_MOVIES';
export const FETCH_SHOW_ON_AIR_MOVIES = 'FETCH_SHOW_ON_AIR_MOVIES';
export const FETCH_TOP_RATED_SHOWS = 'FETCH_TOP_RATED_SHOWS';
export const FETCH_POPULAR_SHOWS = 'FETCH_POPULAR_SHOWS';

//Video/Trailers
export const FETCH_MOVIE_TRAILER = 'FETCH_MOVIE_TRAILER';
